name: Déploiement Railway via NPX

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Node.js (nécessaire pour Railway CLI)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Déployer avec Railway via NPX
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: npx -y @railway/cli up
